<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to hypothesis testing for diversity • breakaway</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/united/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to hypothesis testing for diversity">
<meta property="og:description" content="breakaway">
<meta property="og:image" content="http://adw96.github.io/breakaway/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">breakaway</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">4.7.5</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/breakaway.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/diversity-hypothesis-testing.html">Introduction to hypothesis testing for diversity</a>
    </li>
    <li>
      <a href="../articles/intro-diversity-estimation.html">Introduction to diversity estimation</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/adw96/breakaway/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="diversity-hypothesis-testing_files/header-attrs-2.9/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Introduction to hypothesis testing for diversity</h1>
                        <h4 class="author">Amy Willis</h4>
            
            <h4 class="date">2021-10-07</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/adw96/breakaway/blob/master/vignettes/diversity-hypothesis-testing.Rmd"><code>vignettes/diversity-hypothesis-testing.Rmd</code></a></small>
      <div class="hidden name"><code>diversity-hypothesis-testing.Rmd</code></div>

    </div>

    
    
<p>This tutorial will talk through hypothesis testing for alpha diversity indices using the functions <code>betta</code> and <code>betta_random</code>.</p>
<div id="disclaimer" class="section level2">
<h2 class="hasAnchor">
<a href="#disclaimer" class="anchor"></a>Disclaimer</h2>
<p><em>Disclaimer</em>: If you have not taken a introductory statistics class or devoted serious time to learning introductory statistics, I strongly encourage you to reconsider doing so before ever quoting a p-value or doing modeling of any kind. An introductory statistics class will teach you valuable skills that will serve you well throughout your entire scientific career, including the use and abuse of p-values in science, how to responsibly fit models and test null hypotheses, and an appreciation for how easy it is to inflate the statistical significance of a result. Please equip yourself with the statistical skills and scepticism necessary to responsibly test and discuss null hypothesis significance testing.</p>
</div>
<div id="preliminaries" class="section level2">
<h2 class="hasAnchor">
<a href="#preliminaries" class="anchor"></a>Preliminaries</h2>
<p>Download the latest version of the package from github.</p>
<p>Let’s use the Whitman et al dataset from <code>corncob</code> as our example.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># devtools::install_github("bryandmartin/corncob")</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bryandmartin/corncob">corncob</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"soil_phylo"</span><span class="op">)</span>
<span class="va">soil_phylo</span> <span class="op">%&gt;%</span> <span class="va">sample_data</span> <span class="op">%&gt;%</span> <span class="va">head</span></code></pre></div>
<pre><code>##      Plants DayAmdmt Amdmt ID Day
## S009      1       01     1  D   0
## S204      1       21     1  D   2
## S112      0       11     1  B   1
## S247      0       22     2  F   2
## S026      0       00     0  A   0
## S023      1       00     0  C   0</code></pre>
<p>I’m only going to consider samples amended with biochar, and I want to look at the effect of <code>Day</code>. This will tell us how much diversity in the soil changed from Day 0 to Day 82. (Just to be confusing, Day 82 is called Day 2 in the dataset.)</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">subset_soil</span> <span class="op">&lt;-</span> <span class="va">soil_phylo</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/phyloseq/man/subset_samples-methods.html">subset_samples</a></span><span class="op">(</span><span class="va">Amdmt</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="co"># only biochar</span>
  <span class="fu"><a href="https://rdrr.io/pkg/phyloseq/man/subset_samples-methods.html">subset_samples</a></span><span class="op">(</span><span class="va">Day</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>  <span class="co"># only Days 0 and 82</span></code></pre></div>
<p>I now run breakaway on these samples to get richness estimates, and plot them.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">richness_soil</span> <span class="op">&lt;-</span> <span class="va">subset_soil</span> <span class="op">%&gt;%</span> <span class="va">breakaway</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">richness_soil</span>, physeq<span class="op">=</span><span class="va">subset_soil</span>, color<span class="op">=</span><span class="st">"Day"</span>, shape <span class="op">=</span> <span class="st">"ID"</span><span class="op">)</span></code></pre></div>
<p><img src="diversity-hypothesis-testing_files/figure-html/unnamed-chunk-5-1.png" width="700"></p>
<p>Don’t freak out! Those are wide error bars, but nothing went wrong – it’s just really hard to estimate the true number of unknown species in soil. <code>breakaway</code> was developed to deal with this, and to make sure that we account for that uncertainty when we do inference.</p>
<p>We can get a table of the estimates and their uncertainties as follows:</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">richness_soil</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="va">as_tibble</span></code></pre></div>
<pre><code>## # A tibble: 32 × 7
##    estimate  error lower   upper sample_names name      model            
##       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;     &lt;chr&gt;            
##  1    5257.  203.  4010.  54003. S009         breakaway Kemp             
##  2    5343. 2252.  4317. 316529. S204         breakaway Kemp             
##  3    4609.  978.  2782. 250548. S012         breakaway Kemp             
##  4    5446. 1393.  3864. 299572. S207         breakaway Kemp             
##  5    5359.  143.  4370.  35608. S202         breakaway Kemp             
##  6    3882.  181.  2802.  44399. S007         breakaway Kemp             
##  7    4906. 4787.  3111. 748118. S022         breakaway Kemp             
##  8    5215.  343.  3327. 106472. S024         breakaway Negative Binomial
##  9    4509.   98.9 3443.  24952. S032         breakaway Kemp             
## 10    5070.  114.  4189.  27300. S212         breakaway Kemp             
## # … with 22 more rows</code></pre>
<p>If you haven’t seen a <code>tibble</code> before, it’s like a <code>data.frame</code>, but way better. Already we can see that we only have 10 rows printed as opposed to the usual bagillion.</p>
</div>
<div id="inference" class="section level2">
<h2 class="hasAnchor">
<a href="#inference" class="anchor"></a>Inference</h2>
<p>The first step to doing inference is to decide on your design matrix. We need to grab our covariates into a data frame (or tibble), so let’s start by doing that:</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">meta</span> <span class="op">&lt;-</span> <span class="va">subset_soil</span> <span class="op">%&gt;%</span>
  <span class="va">sample_data</span> <span class="op">%&gt;%</span>
  <span class="va">as_tibble</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span><span class="st">"sample_names"</span> <span class="op">=</span> <span class="va">subset_soil</span> <span class="op">%&gt;%</span> <span class="va">sample_names</span> <span class="op">)</span></code></pre></div>
<p>That warning is not a problem – it’s just telling us that it’s not a phyloseq object anymore.</p>
<p>Suppose we want to fit the model with Day as a fixed effect. Here’s how we do that,</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">combined_richness</span> <span class="op">&lt;-</span> <span class="va">meta</span> <span class="op">%&gt;%</span>
  <span class="fu">left_join</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">richness_soil</span><span class="op">)</span>,
            by <span class="op">=</span> <span class="st">"sample_names"</span><span class="op">)</span>
<span class="co"># Old way (still works)</span>
<span class="va">bt_day_fixed</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/betta.html">betta</a></span><span class="op">(</span>chats <span class="op">=</span> <span class="va">combined_richness</span><span class="op">$</span><span class="va">estimate</span>,
                      ses <span class="op">=</span> <span class="va">combined_richness</span><span class="op">$</span><span class="va">error</span>,
                      X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span><span class="op">~</span><span class="va">Day</span>, data <span class="op">=</span> <span class="va">combined_richness</span><span class="op">)</span><span class="op">)</span>
<span class="co"># Fancy new way -- thanks to Sarah Teichman for implementing!</span>
<span class="va">bt_day_fixed</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/betta.html">betta</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">estimate</span> <span class="op">~</span> <span class="va">Day</span>, 
                      ses <span class="op">=</span> <span class="va">error</span>, data <span class="op">=</span> <span class="va">combined_richness</span><span class="op">)</span>
<span class="va">bt_day_fixed</span><span class="op">$</span><span class="va">table</span></code></pre></div>
<pre><code>##             Estimates Standard Errors p-values
## (Intercept) 4547.1078        125.8542    0.000
## Day2         139.5325        170.1855    0.412</code></pre>
<p>So we see an estimated increase in richness after 82 days of 122 taxa, with the standard error in the estimate of 171. A hypothesis test for a change in richness would <em>not be rejected</em> at any reasonable cut-off (p = 0.475).</p>
<p>Alternatively, we could fit the model with plot ID as a random effect. Here’s how we do that:</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Old way (still works)</span>
<span class="va">bt_day_fixed_id_random</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/betta_random.html">betta_random</a></span><span class="op">(</span>chats <span class="op">=</span> <span class="va">combined_richness</span><span class="op">$</span><span class="va">estimate</span>,
                                       ses <span class="op">=</span> <span class="va">combined_richness</span><span class="op">$</span><span class="va">error</span>,
                                       X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span><span class="op">~</span><span class="va">Day</span>, data <span class="op">=</span> <span class="va">combined_richness</span><span class="op">)</span>,
                                       groups<span class="op">=</span><span class="va">combined_richness</span><span class="op">$</span><span class="va">ID</span><span class="op">)</span>
<span class="co"># Fancy new way </span>
<span class="va">bt_day_fixed_id_random</span> <span class="op">&lt;-</span>
  <span class="fu"><a href="../reference/betta_random.html">betta_random</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">estimate</span> <span class="op">~</span> <span class="va">Day</span> <span class="op">|</span> <span class="va">ID</span>, 
               ses <span class="op">=</span> <span class="va">error</span>,  data <span class="op">=</span> <span class="va">combined_richness</span><span class="op">)</span>
<span class="va">bt_day_fixed_id_random</span><span class="op">$</span><span class="va">table</span></code></pre></div>
<pre><code>##             Estimates Standard Errors p-values
## (Intercept) 4475.4249        119.2010     0.00
## Day2         257.7939        161.2601     0.11</code></pre>
<p>Under this different model, we see an estimated increase in richness after 82 days of 258 taxa, with the standard error in the estimate of 161. A hypothesis test for a change in richness still would <em>not be rejected</em> at any reasonable cut-off (p = 0.11).</p>
<p>If you choose to use the old way, the structure of <code>betta_random</code> is to input your design matrix as <code>X</code>, and your random effects as <code>groups</code>, where the latter is a categorical variable. Otherwise, the input looks like how you would hand this off to a regular mixed effects model in the package <code>lme4</code>!</p>
</div>
<div id="using-betta-with-divnet" class="section level1">
<h1 class="hasAnchor">
<a href="#using-betta-with-divnet" class="anchor"></a>Using <code>betta</code> with DivNet</h1>
<p>Maybe you don’t care about richness… but you care about Shannon or Simpson diversity! <a href="https://github.com/adw96/DivNet"><code>DivNet</code></a> is our <code>R</code> package for estimating Shannon and Simpson diversity.</p>
<p>DivNet can be slow when you have a large number of taxa (but we are working on it!), so to illustrate we are going to estimate phylum-level Shannon diversity:</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">soil_phylum</span> <span class="op">&lt;-</span> <span class="va">subset_soil</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/phyloseq/man/tax_glom.html">tax_glom</a></span><span class="op">(</span>taxrank<span class="op">=</span><span class="st">"Phylum"</span><span class="op">)</span></code></pre></div>
<p>Easter egg: <code><a href="https://rdrr.io/pkg/phyloseq/man/tax_glom.html">phyloseq::tax_glom</a></code> can be incredibly slow! <a href="https://github.com/mikemc">Mike McLaren</a> is a total champ and rewrote it faster – check out his package <a href="https://github.com/mikemc/speedyseq"><code>speedyseq</code></a> and <code><a href="https://mikemc.github.io/speedyseq/reference/tax_glom.html">speedyseq::tax_glom</a></code> in particular.</p>
<p>Let’s treat all samples as independent observations (<code>X = NULL</code>) and fit the DivNet model:</p>
<p>(Check out the full documentation for details, including how to run in parallel)</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dv</span> <span class="op">&lt;-</span> <span class="fu">DivNet</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/DivNet/man/divnet.html">divnet</a></span><span class="op">(</span><span class="va">soil_phylum</span>, X <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></code></pre></div>
<p>This produces an object containing common diversity estimates:</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dv</span></code></pre></div>
<pre><code>## An object of class `diversityEstimates` with the following elements:
##   -  shannon 
##   -  simpson 
##   -  bray-curtis 
##   -  euclidean 
##   -  shannon-variance 
##   -  simpson-variance 
##   -  bray-curtis-variance 
##   -  euclidean-variance 
##   -  X 
##   -  fitted_z 
## Access individual components with, e.g., object$shannon and object$`shannon-variance`
## Use function testDiversity() to test hypotheses about diversity</code></pre>
<p>We can look at the first few Shannon diversity estimates with the following:</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">combined_shannon</span> <span class="op">&lt;-</span> <span class="va">meta</span> <span class="op">%&gt;%</span>
  <span class="fu">left_join</span><span class="op">(</span><span class="va">dv</span><span class="op">$</span><span class="va">shannon</span> <span class="op">%&gt;%</span> <span class="va">summary</span>,
            by <span class="op">=</span> <span class="st">"sample_names"</span><span class="op">)</span>
<span class="va">combined_shannon</span></code></pre></div>
<pre><code>## # A tibble: 32 × 12
##    Plants DayAmdmt Amdmt ID    Day   sample_names estimate   error lower upper
##    &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 1      01       1     D     0     S009             2.04 0.00350  2.04  2.05
##  2 1      21       1     D     2     S204             1.98 0.00113  1.98  1.98
##  3 0      01       1     B     0     S012             2.00 0.00492  1.99  2.01
##  4 0      21       1     B     2     S207             2.04 0.00307  2.04  2.05
##  5 0      21       1     B     2     S202             2.01 0.00203  2.01  2.02
##  6 0      01       1     B     0     S007             2.04 0.00483  2.03  2.05
##  7 0      01       1     B     0     S022             2.04 0.00288  2.03  2.04
##  8 1      01       1     D     0     S024             2.01 0.00377  2.00  2.01
##  9 0      01       1     B     0     S032             1.99 0.00439  1.99  2.00
## 10 0      21       1     B     2     S212             2.02 0.00235  2.02  2.03
## # … with 22 more rows, and 2 more variables: name &lt;chr&gt;, model &lt;chr&gt;</code></pre>
<p>You might notice that the estimates are not different from the plug-in estimate (only because we used <code>X = NULL</code>), but we have standard errors! That’s the real advantage of using DivNet :)</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">bt_day_fixed_id_random</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/betta_random.html">betta_random</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">estimate</span> <span class="op">~</span> <span class="va">Day</span> <span class="op">|</span> <span class="va">ID</span>, 
               ses <span class="op">=</span> <span class="va">error</span>,  data <span class="op">=</span> <span class="va">combined_shannon</span><span class="op">)</span>
<span class="va">bt_day_fixed_id_random</span><span class="op">$</span><span class="va">table</span></code></pre></div>
<pre><code>##                Estimates Standard Errors p-values
## (Intercept)  2.016085066     0.004695753    0.000
## Day2        -0.007620836     0.006591627    0.248</code></pre>
<p>and similarly for no random effects.</p>
<p>If you are interested in generating confidence intervals for and testing hypotheses about linear combinations of fixed effects estimated in a <code>betta</code> or <code>betta_random</code> model, we recommend using the <code>betta_lincom</code> function.</p>
<p>For example, to generate a confidence interval for <span class="math inline">\(\beta_0 + \beta_1\)</span> (i.e., intercept plus ‘Day2’ coefficient, or in other words, the mean Shannon diversity in soils on day 82 of the experiment) in the Shannon diversity model we fit in the previous code chunk, we run the following code:</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/betta_lincom.html">betta_lincom</a></span><span class="op">(</span>fitted_betta <span class="op">=</span> <span class="va">bt_day_fixed_id_random</span>,
             linear_com <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span>,
             signif_cutoff <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span></code></pre></div>
<pre><code>##   Estimates Standard Errors Lower CIs Upper CIs p-values
## 1  2.008464     0.006591627  1.995545  2.021384  &lt; 1e-20</code></pre>
<p>Here, we’ve set the <code>linear_com</code> argument equal to <code><a href="https://rdrr.io/r/base/c.html">c(1,1)</a></code> to tell <code>betta_lincom</code> to construct a confidence interval for <span class="math inline">\(1 \times \beta_0 + 1 \times \beta_1\)</span>. Because we set <code>signif_cutoff</code> equal to <span class="math inline">\(0.05\)</span>, <code>betta_lincom</code> returns a <span class="math inline">\(95\% = (1 - 0.05)*100\%\)</span> confidence interval. The p-value reported here is for a test of the null hypothesis that <span class="math inline">\(1 \times \beta_0 + 1 \times \beta_1 = 0\)</span> – unsurprisingly, this is small. (If you are confused about why this is “unsurprising,” remember that <span class="math inline">\(\beta_0 + \beta_1\)</span> represents a mean Shannon diversity in soils on day 82 of the experiment of Whitman et al. When can a Shannon diversity be zero?)</p>
<p>The syntax and output using <code>betta_lincom</code> with a <code>betta</code> object as input is exactly the same as with a <code>betta_random</code> object, so we haven’t included a separate example for this case.</p>
<p>And there you have it! That’s how to do hypothesis testing for diversity!</p>
<p>If you use our tools, please don’t forget to cite them!</p>
<ul>
<li>
<code>breakaway</code>: Willis &amp; Bunge. (2015). <em>Estimating diversity via frequency ratios</em>. Biometrics. <a href="https://doi.org/10.1111/biom.12332">doi:10.1111/biom.12332</a>.</li>
<li>
<code>DivNet</code>: Willis &amp; Martin. (2018+). <em>DivNet: Estimating diversity in networked communities</em>. bioRxiv. <a href="https://doi.org/10.1101/305045">10.1101/305045</a>.</li>
<li>
<code>betta</code>: Willis, Bunge &amp; Whitman. (2016). <em>Improved detection of changes in species richness in high diversity microbial communities</em>. Journal of the Royal Statistical Society: Series C. <a href="https://doi.org/10.1111/rssc.12206">doi:10.1111/rssc.12206</a>.</li>
</ul>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Amy Willis, Bryan D Martin, Pauline Trinh, Sarah Teichman, David Clausen, Kathryn Barger, John Bunge.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
